test:
  browser: firefox
  startUrl: http://www.hauts-de-seine.gouv.fr
  suites:
    - htmlrunner_suite

logging.level.org.openqa: ERROR
logging.level.de.computerlyrik: INFO

spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: app.ws.client@gmail.com
spring.mail.password: V3ry_Str0ng_P@ssword
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.starttls.required: true
